name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/liuxf2/blog-code    #自己服务器的项目地址
            git reset --hard
            git pull    #同步            
          host: ${{ secrets.REMOTE_HOST }} #服务器ip
          user: ${{ secrets.REMOTE_USER }} #服务器user
          pass: ${{ secrets.PASSWORD }} #服务器密码